name: Build with VSCode Tasks

on: [push, pull_request]

jobs:
  build:
    name: Build Project
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: ${{ matrix.architecture }}

    - name: Build Code
      run: |
        .\build.cmd
      working-directory: ${{ github.workspace }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: minimize-to-tray-${{ format-date('_YYYYMMDD', github.event.run_started_at) }}
        path: ${{ github.workspace }}\minimize-to-tray.exe

