name: Build with VSCode Tasks

on: workflow_dispatch

jobs:
  build:
    name: Build Project
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: ${{ matrix.architecture }}

    - name: Build Code
      run: |
        .\build.cmd
      working-directory: ${{ github.workspace }}

    - name: Set date variable
      run: |
        $date = Get-Date -Format "_yyyyMMdd"
        echo "ARTIFACT_NAME=minimize-to-tray-$date" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append
      shell: pwsh
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ github.workspace }}\minimize-to-tray.exe

