name: Build with VSCode Tasks

on: [push, pull_request]

jobs:
  build:
    name: Build Project
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSVC environment
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '[16.0, 17.0)' # 安装16.0到17.0之间的最新版本

    - name: Setup MSBuild (x64)
      if: always()
      id: setup_msbuild_path_x64
      uses: ./
      with:
        vs-prerelease: true
        msbuild-architecture: 'x64'

    - name: echo msbuild path
      run: |
        echo "ARM PATH: ${{ steps.setup_msbuild_path_x64.outputs.msbuildPath }}"




    - name: Build Resource
      run: |
        .\vc.bat rc.exe /nologo ${{ github.workspace }}\minimize-to-tray.rc
      working-directory: ${{ github.workspace }}

    - name: Build Code
      run: |
        .\vc.bat cl.exe /nologo /Zi /EHsc /DUNICODE /D_UNICODE /Fe:${{ github.workspace }}\minimize-to-tray.exe ${{ github.workspace }}\*.c User32.lib ${{ github.workspace }}\minimize-to-tray.res /link /subsystem:windows
      working-directory: ${{ github.workspace }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows Build
        path: ${{ github.workspace }}\minimize-to-tray.exe

